package provider

import (
	"context"
	"time"

	"github.com/kumahq/kuma/pkg/core/resources/manager"
	"github.com/kumahq/kuma/pkg/core/runtime/component"
	"github.com/kumahq/kuma/pkg/metrics"
	"github.com/kumahq/kuma/pkg/util/ticker"
)

// 1. Take all meshidentities
// 2. Generate for autogenerated if not created
// 3. Set status?

type MeshIdentityGenerator struct {
	rm manager.ResourceManager
}

func NewGenerator(
	interval time.Duration,
	metrics metrics.Metrics,
) (component.Component, error) {
	task, err := ticker.NewPeriodicTask(
		"mesh-identity",
		interval,
		metrics,
		func(_ context.Context) error {

		},
		func(_ context.Context) error {
			return nil
		}, false)
	if err != nil {
		return nil, err
	}

	return task, nil
}

func EnsureBackends() {

}
