//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Builtin) DeepCopyInto(out *Builtin) {
	*out = *in
	if in.DataplaneCertificate != nil {
		in, out := &in.DataplaneCertificate, &out.DataplaneCertificate
		*out = new(DataplaneCertificate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Builtin.
func (in *Builtin) DeepCopy() *Builtin {
	if in == nil {
		return nil
	}
	out := new(Builtin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataplaneCertificate) DeepCopyInto(out *DataplaneCertificate) {
	*out = *in
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataplaneCertificate.
func (in *DataplaneCertificate) DeepCopy() *DataplaneCertificate {
	if in == nil {
		return nil
	}
	out := new(DataplaneCertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshIdentity) DeepCopyInto(out *MeshIdentity) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	if in.SpiffeID != nil {
		in, out := &in.SpiffeID, &out.SpiffeID
		*out = new(SpiffeID)
		**out = **in
	}
	in.Provider.DeepCopyInto(&out.Provider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshIdentity.
func (in *MeshIdentity) DeepCopy() *MeshIdentity {
	if in == nil {
		return nil
	}
	out := new(MeshIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Provided) DeepCopyInto(out *Provided) {
	*out = *in
	in.Certificate.DeepCopyInto(&out.Certificate)
	in.PrivateKey.DeepCopyInto(&out.PrivateKey)
	if in.DataplaneCertificate != nil {
		in, out := &in.DataplaneCertificate, &out.DataplaneCertificate
		*out = new(DataplaneCertificate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Provided.
func (in *Provided) DeepCopy() *Provided {
	if in == nil {
		return nil
	}
	out := new(Provided)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Provider) DeepCopyInto(out *Provider) {
	*out = *in
	if in.Builtin != nil {
		in, out := &in.Builtin, &out.Builtin
		*out = new(Builtin)
		(*in).DeepCopyInto(*out)
	}
	if in.Provided != nil {
		in, out := &in.Provided, &out.Provided
		*out = new(Provided)
		(*in).DeepCopyInto(*out)
	}
	if in.Spire != nil {
		in, out := &in.Spire, &out.Spire
		*out = new(Spire)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Provider.
func (in *Provider) DeepCopy() *Provider {
	if in == nil {
		return nil
	}
	out := new(Provider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Selector) DeepCopyInto(out *Selector) {
	*out = *in
	if in.Dataplane != nil {
		in, out := &in.Dataplane, &out.Dataplane
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Selector.
func (in *Selector) DeepCopy() *Selector {
	if in == nil {
		return nil
	}
	out := new(Selector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpiffeID) DeepCopyInto(out *SpiffeID) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpiffeID.
func (in *SpiffeID) DeepCopy() *SpiffeID {
	if in == nil {
		return nil
	}
	out := new(SpiffeID)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Spire) DeepCopyInto(out *Spire) {
	*out = *in
	if in.Agent != nil {
		in, out := &in.Agent, &out.Agent
		*out = new(SpireAgent)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Spire.
func (in *Spire) DeepCopy() *Spire {
	if in == nil {
		return nil
	}
	out := new(Spire)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireAgent) DeepCopyInto(out *SpireAgent) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireAgent.
func (in *SpireAgent) DeepCopy() *SpireAgent {
	if in == nil {
		return nil
	}
	out := new(SpireAgent)
	in.DeepCopyInto(out)
	return out
}
