package meshproxy

import (
	"fmt"
	"time"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	"golang.org/x/sync/errgroup"

	mesh_proto "github.com/kumahq/kuma/v2/api/mesh/v1alpha1"
	meshidentity_api "github.com/kumahq/kuma/v2/pkg/core/resources/apis/meshidentity/api/v1alpha1"
	meshtrust_api "github.com/kumahq/kuma/v2/pkg/core/resources/apis/meshtrust/api/v1alpha1"
	"github.com/kumahq/kuma/v2/pkg/core/resources/model"
	"github.com/kumahq/kuma/v2/pkg/core/resources/model/rest"
	"github.com/kumahq/kuma/v2/pkg/kds/hash"
	"github.com/kumahq/kuma/v2/pkg/test/resources/builders"
	. "github.com/kumahq/kuma/v2/test/framework"
	"github.com/kumahq/kuma/v2/test/framework/client"
	"github.com/kumahq/kuma/v2/test/framework/deployments/democlient"
	"github.com/kumahq/kuma/v2/test/framework/deployments/testserver"
	"github.com/kumahq/kuma/v2/test/framework/deployments/zoneproxy"
	"github.com/kumahq/kuma/v2/test/framework/envs/multizone"
)

func Connectivity() {
	namespace := "meshproxy"
	meshName := "meshproxy"

	BeforeAll(func() {
		Expect(NewClusterSetup().
			Install(Yaml(
				builders.Mesh().
					WithName(meshName).
					WithMeshServicesEnabled(mesh_proto.Mesh_MeshServices_Exclusive),
			)).
			Install(MeshTrafficPermissionAllowAllUniversal(meshName)).
			Setup(multizone.Global)).To(Succeed())
		Expect(WaitForMesh(meshName, multizone.Zones())).To(Succeed())

		group := errgroup.Group{}
		NewClusterSetup().
			Install(NamespaceWithSidecarInjection(namespace)).
			Install(Parallel(
				testserver.Install(
					testserver.WithNamespace(namespace),
					testserver.WithMesh(meshName),
					testserver.WithEchoArgs("echo", "--instance", "kube-test-server-1"),
				),
				democlient.Install(democlient.WithNamespace(namespace), democlient.WithMesh(meshName)),
				zoneproxy.Install(
					zoneproxy.WithNamespace(namespace),
					zoneproxy.WithMesh(meshName),
					zoneproxy.WithIngressPort(10001),
					zoneproxy.WithWorkload("zone-proxy-ingress"),
					zoneproxy.IngressOnly(),
				),
				zoneproxy.Install(
					zoneproxy.WithNamespace(namespace),
					zoneproxy.WithMesh(meshName),
					zoneproxy.WithEgressPort(10002),
					zoneproxy.WithWorkload("zone-proxy-egress"),
					zoneproxy.EgressOnly(),
				),
			)).
			SetupInGroup(multizone.KubeZone1, &group)

		NewClusterSetup().
			Install(NamespaceWithSidecarInjection(namespace)).
			Install(Parallel(
				testserver.Install(
					testserver.WithNamespace(namespace),
					testserver.WithMesh(meshName),
					testserver.WithEchoArgs("echo", "--instance", "kube-test-server-2"),
				),
				zoneproxy.Install(
					zoneproxy.WithNamespace(namespace),
					zoneproxy.WithMesh(meshName),
					zoneproxy.WithIngressPort(10001),
					zoneproxy.WithWorkload("zone-proxy-ingress"),
					zoneproxy.IngressOnly(),
				),
				zoneproxy.Install(
					zoneproxy.WithNamespace(namespace),
					zoneproxy.WithMesh(meshName),
					zoneproxy.WithEgressPort(10002),
					zoneproxy.WithWorkload("zone-proxy-egress"),
					zoneproxy.EgressOnly(),
				),
			)).
			SetupInGroup(multizone.KubeZone2, &group)

		NewClusterSetup().
			Install(Parallel(
				DemoClientUniversal("demo-client", meshName, WithTransparentProxy(true), WithWorkload("demo-client")),
				TestServerUniversal("test-server", meshName, WithArgs([]string{"echo", "--instance", "uni-test-server"}), WithWorkload("test-server")),
				zoneproxy.Install(
					zoneproxy.WithMesh(meshName),
					zoneproxy.WithIngressPort(10001),
					zoneproxy.WithWorkload("zone-proxy-ingress"),
					zoneproxy.IngressOnly(),
				),
				zoneproxy.Install(
					zoneproxy.WithMesh(meshName),
					zoneproxy.WithEgressPort(10002),
					zoneproxy.WithWorkload("zone-proxy-egress"),
					zoneproxy.EgressOnly(),
				),
			)).
			SetupInGroup(multizone.UniZone1, &group)
		Expect(group.Wait()).To(Succeed())

		// MeshZoneAddress must be created manually for Universal zones.
		// On Kubernetes it is auto-generated by the meshzoneaddress controller.
		ingressIP := multizone.UniZone1.GetApp("zone-proxy-ingress").GetIP()
		Expect(NewClusterSetup().
			Install(YamlUniversal(fmt.Sprintf(`
type: MeshZoneAddress
name: zone-proxy-ingress
mesh: %s
labels:
  kuma.io/origin: zone
  kuma.io/zone: %s
spec:
  address: %s
  port: %d
`, meshName, multizone.UniZone1.ZoneName(), ingressIP, 10001))).
			Setup(multizone.UniZone1)).To(Succeed())

		// Create MeshIdentity for zone-proxy mTLS
		meshIdentityYAML := fmt.Sprintf(`
type: MeshIdentity
name: identity
mesh: %s
spec:
  selector:
    dataplane:
      matchLabels: {}
  spiffeID:
    trustDomain: "{{ .Mesh }}.{{ .Zone }}.mesh.local"
  provider:
    type: Bundled
    bundled:
      meshTrustCreation: Enabled
      insecureAllowSelfSigned: true
      certificateParameters:
        expiry: 24h
      autogenerate:
        enabled: true
`, meshName)
		Expect(NewClusterSetup().
			Install(YamlUniversal(meshIdentityYAML)).
			Setup(multizone.Global)).To(Succeed())

		hashedIdentityName := hash.HashedName(meshName, "identity")
		Expect(WaitForResource(
			meshidentity_api.MeshIdentityResourceTypeDescriptor,
			model.ResourceKey{Mesh: meshName, Name: fmt.Sprintf("%s.%s", hashedIdentityName, Config.KumaNamespace)},
			multizone.KubeZone1, multizone.KubeZone2,
		)).To(Succeed())

		// Fetch auto-generated MeshTrust from each zone and publish to Global
		// so KDS distributes it to all zones, enabling cross-zone mTLS.
		getMeshTrust := func(hashValues ...string) *meshtrust_api.MeshTrust {
			var trust *meshtrust_api.MeshTrust
			Eventually(func(g Gomega) {
				out, err := multizone.Global.GetKumactlOptions().RunKumactlAndGetOutput(
					"get", "meshtrust", "-m", meshName,
					hash.HashedName(meshName, hashedIdentityName, hashValues...),
					"-ojson",
				)
				g.Expect(err).ToNot(HaveOccurred())
				r, err := rest.JSON.Unmarshal([]byte(out), meshtrust_api.MeshTrustResourceTypeDescriptor)
				g.Expect(err).ToNot(HaveOccurred())
				trust = r.GetSpec().(*meshtrust_api.MeshTrust)
			}, "30s", "1s").Should(Succeed())
			return trust
		}

		installTrustToGlobal := func(trust *meshtrust_api.MeshTrust, sourceZoneName string) {
			yaml := builders.MeshTrust().
				WithName("meshtrust-of-zone-" + sourceZoneName).
				WithMesh(meshName).
				WithCA(trust.CABundles[0].PEM.Value).
				WithTrustDomain(trust.TrustDomain).
				UniYaml()
			Expect(NewClusterSetup().Install(YamlUniversal(yaml)).Setup(multizone.Global)).To(Succeed())
		}

		trustZone1 := getMeshTrust(multizone.KubeZone1.Name(), Config.KumaNamespace)
		installTrustToGlobal(trustZone1, multizone.KubeZone1.Name())

		trustZone2 := getMeshTrust(multizone.KubeZone2.Name(), Config.KumaNamespace)
		installTrustToGlobal(trustZone2, multizone.KubeZone2.Name())

		trustZone4 := getMeshTrust(multizone.UniZone1.Name())
		installTrustToGlobal(trustZone4, multizone.UniZone1.Name())
	})

	AfterEachFailure(func() {
		DebugUniversal(multizone.Global, meshName)
		DebugUniversal(multizone.UniZone1, meshName)
		DebugKube(multizone.KubeZone1, meshName, namespace)
		DebugKube(multizone.KubeZone2, meshName, namespace)
	})

	E2EAfterAll(func() {
		Expect(multizone.KubeZone1.TriggerDeleteNamespace(namespace)).To(Succeed())
		Expect(multizone.KubeZone2.TriggerDeleteNamespace(namespace)).To(Succeed())
		Expect(multizone.UniZone1.DeleteMeshApps(meshName)).To(Succeed())
		Expect(multizone.Global.DeleteMesh(meshName)).To(Succeed())
	})

	It("should route cross-zone traffic via new zone proxies", func() {
		time.Sleep(1 * time.Hour)
		// Kubernetes client -> Universal zone
		Eventually(func(g Gomega) {
			response, err := client.CollectEchoResponse(
				multizone.KubeZone1, "demo-client",
				fmt.Sprintf("http://test-server.svc.%s.mesh.local:80", multizone.UniZone1.ZoneName()),
				client.FromKubernetesPod(namespace, "demo-client"),
			)
			g.Expect(err).ToNot(HaveOccurred())
			g.Expect(response.Instance).To(Equal("uni-test-server"))
		}, "30s", "1s").Should(Succeed())

		// Universal client -> Kubernetes zone 1
		Eventually(func(g Gomega) {
			response, err := client.CollectEchoResponse(
				multizone.UniZone1, "demo-client",
				fmt.Sprintf("http://test-server.%s.svc.%s.mesh.local:80", namespace, multizone.KubeZone1.ZoneName()),
			)
			g.Expect(err).ToNot(HaveOccurred())
			g.Expect(response.Instance).To(Equal("kube-test-server-1"))
		}, "30s", "1s").Should(Succeed())

		// Universal client -> Kubernetes zone 2
		Eventually(func(g Gomega) {
			response, err := client.CollectEchoResponse(
				multizone.UniZone1, "demo-client",
				fmt.Sprintf("http://test-server.%s.svc.%s.mesh.local:80", namespace, multizone.KubeZone2.ZoneName()),
			)
			g.Expect(err).ToNot(HaveOccurred())
			g.Expect(response.Instance).To(Equal("kube-test-server-2"))
		}, "30s", "1s").Should(Succeed())
	})
}
